# Generated by Django 3.2.5 on 2021-07-01 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=120)),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='catalogs.customertype')),
            ],
        ),
    ]
