# Generated by Django 3.2.5 on 2021-07-01 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.IntegerField(unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('deliver_date', models.DateField(null=True)),
                ('urgent', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalogs.ordertype')),
            ],
        ),
        migrations.CreateModel(
            name='DetailOrderDistributionCenter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_center_orders', to='orders.order')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalogs.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DetailOrderBranchOffice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=20)),
                ('branch_office_code', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_office_orders', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='DetailOrderAssociatedCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=20)),
                ('partner_code', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associated_company_orders', to='orders.order')),
            ],
        ),
    ]
