# Generated by Django 3.2.5 on 2021-07-01 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_vendors'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='articles.article')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles_details', to='orders.order')),
            ],
        ),
    ]
