# Generated by Django 3.2.5 on 2021-07-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_articlesorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='articlesorder',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
